// src/app/components/devices.ts
import { Device } from "../types";
import { fetchThingSpeakData, updateDeviceWithThingSpeakData } from "./thingspeak";

// Function to get the latest device data
export async function getDevices(): Promise<Device[]> {
    const baseDevices: Device[] = [
        {
            id: "1",
            name: "Command Center",
            position: [43.0481, -76.1474] as [number, number],
            status: "Online",
            temperature: 25.5,
            humidity: 60.0,
            pressure: 1013.2,
            airQuality: 100,
            coLevel: 0,
            combustibleGas: 0,
            waterQuality: 0,
            type: "official",
            iconColor: "#3b82f6",
            connectedTo: ["2", "3", "4"],
            signalStrength: 95,
            batteryLevel: 100,
        },
        {
            id: "2",
            name: "Survival Kit #1",
            position: [43.0592, -76.1435] as [number, number],
            status: "Online",
            temperature: 26.0,
            humidity: 55.0,
            pressure: 1012.8,
            airQuality: 150,
            coLevel: 5,
            combustibleGas: 10,
            waterQuality: 200,
            type: "kit",
            iconColor: "#10b981",
            connectedTo: ["1", "3", "5", "7"],
            signalStrength: 85,
            batteryLevel: 92,
        },
        {
            id: "3",
            name: "Survival Kit #2",
            position: [43.0483, -76.1586] as [number, number],
            status: "Online",
            temperature: 24.5,
            humidity: 62.0,
            pressure: 1013.5,
            airQuality: 120,
            coLevel: 3,
            combustibleGas: 8,
            waterQuality: 180,
            type: "kit",
            iconColor: "#10b981",
            connectedTo: ["1", "2", "4", "6", "8"],
            signalStrength: 45,
            batteryLevel: 78,
        },
        {
            id: "4",
            name: "Survival Kit #3",
            position: [43.0374, -76.1467] as [number, number],
            status: "Online",
            temperature: 0,
            humidity: 0,
            pressure: 0,
            airQuality: 0,
            coLevel: 0,
            combustibleGas: 0,
            waterQuality: 0,
            type: "kit",
            iconColor: "#10b981",
            connectedTo: ["1", "3", "5", "9"],
            signalStrength: 75,
            batteryLevel: 88,
        },
        {
            id: "5",
            name: "Survival Kit #4",
            position: [43.0525, -76.1325] as [number, number],
            status: "Online",
            temperature: 25.2,
            humidity: 59.0,
            pressure: 1013.0,
            airQuality: 130,
            coLevel: 4,
            combustibleGas: 12,
            waterQuality: 220,
            type: "kit",
            iconColor: "#10b981",
            connectedTo: ["2", "4", "6", "7"],
            signalStrength: 80,
            batteryLevel: 95,
        },
        {
            id: "6",
            name: "Survival Kit #5",
            position: [43.0436, -76.1625] as [number, number],
            status: "Online",
            temperature: 24.8,
            humidity: 61.0,
            pressure: 1012.2,
            airQuality: 140,
            coLevel: 6,
            combustibleGas: 15,
            waterQuality: 240,
            type: "kit",
            iconColor: "#10b981",
            connectedTo: ["3", "5", "8"],
            signalStrength: 65,
            batteryLevel: 82,
        },
        {
            id: "7",
            name: "Survival Kit #6",
            position: [43.0625, -76.1525] as [number, number],
            status: "Online",
            temperature: 25.1,
            humidity: 57.0,
            pressure: 1013.8,
            airQuality: 110,
            coLevel: 2,
            combustibleGas: 5,
            waterQuality: 160,
            type: "kit",
            iconColor: "#10b981",
            connectedTo: ["2", "5", "8"],
            signalStrength: 70,
            batteryLevel: 90,
        },
        {
            id: "8",
            name: "Survival Kit #7",
            position: [43.0385, -76.1685] as [number, number],
            status: "Online",
            temperature: 24.3,
            humidity: 63.0,
            pressure: 1011.5,
            airQuality: 160,
            coLevel: 7,
            combustibleGas: 18,
            waterQuality: 260,
            type: "kit",
            iconColor: "#10b981",
            connectedTo: ["3", "6", "7", "9"],
            signalStrength: 55,
            batteryLevel: 75,
        },
        {
            id: "9",
            name: "Survival Kit #8",
            position: [43.0275, -76.1385] as [number, number],
            status: "Online",
            temperature: 25.7,
            humidity: 56.0,
            pressure: 1012.0,
            airQuality: 100,
            coLevel: 1,
            combustibleGas: 3,
            waterQuality: 140,
            type: "kit",
            iconColor: "#10b981",
            connectedTo: ["4", "8"],
            signalStrength: 60,
            batteryLevel: 85,
        },
    ];

    try {
        // Fetch ThingSpeak data
        const thingSpeakData = await fetchThingSpeakData();
        
        // Update Survival Kit 3 with ThingSpeak data
        const updatedDevices = baseDevices.map(device => {
            if (device.id === "4") { // Survival Kit 3
                return updateDeviceWithThingSpeakData(device, thingSpeakData);
            }
            return device;
        });

        return updatedDevices;
    } catch (error) {
        console.error('Error updating devices with ThingSpeak data:', error);
        return baseDevices;
    }
}
